spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eDoroha
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: eDoroha
  config:
    import:
      - "classpath:graphhopper.yml"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.web.HttpLogging: WARN